### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by jkroepke**
If you do a release next time, the ci will create prebuilt artifacts.

### CODE REVIEW

**Comment by jkroepke** [comment]
Take a look at https://github.com/jkroepke/sonar-gitlab-plugin/actions/runs/523464100 to see this in action.

**Comment by lucasoares** [comment]
Seems ok to me.

To create the tag I suggest to create a manual github action and use maven release plugin.
If you look to current artifacts, its created based on a -SNAPSHOT. I just installed the latest release artifact:
image

This not good since you never know if you really have the stable version installed on sonarqube or a old SNAPSHOT.

**Comment by lucasoares** [comment]
Seems ok to me.

@jkroepke To create the tag I suggest to create a manual github action and use maven release plugin.
If you look to current artifacts, its created based on a -SNAPSHOT. I just installed the latest release artifact:
image

This not good since you never know if you really have the stable version installed on sonarqube or a old SNAPSHOT.

**Comment by jkroepke** [comment]
Just to know, the current artifacts in my forked just created manually.

I'm using maven release plugin here, too https://github.com/adorsys/keycloak-config-cli 

I guess push artifacts from a git tag should give a version without SNAPSHOT back.


Currently I'm just running maven release plugin locally. did you prefer to do this via gh actions? I could provide such an action.

**Comment by javamachr** [comment]
I guess action on tag created event would be the right choice. Also readme.md contains badge with link to build of original fork - might be worth replacing with action status badge.

**Comment by lucasoares** [comment]
@javamachr @jkroepke 
Yes, it should give a version without SNAPSHOT but the tag and the artifact was created manually for 4.3.0 and it has the SNAPSHOT: https://github.com/javamachr/sonar-gitlab-plugin/blob/4.3.0/pom.xml

Now the 4.3.1 has also 4.3.0-SNAPSHOT: https://github.com/javamachr/sonar-gitlab-plugin/blob/4.3.1/pom.xml

So if you run `mvn package` in the tag branch you will get a jar with the incorrect version.

Before a release you always should increase the version. either manually or using maven release plugin.

**Pull request merged**
